server:
  port: 17001
  servlet:
    context-path: /provider/

#  设置服务名
spring:
  application:
    name: wb-provider

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:17000/eureka/ #  设置注册中心地址
  instance:
    instance-id: ${spring.application.name}:${server.port} #  实例名称
    prefer-ip-address: true  # 使用ip注册，默认未false使用hostname